package com.livelike.engagementsdkapi

/**
 * A LiveLikeUser is the representation of a user in the library.
 *
 * @property userId The id of the user. This value is defined by LiveLike CMS.
 * @property userName The username of the user. The default value is generated by LiveLike CMS, then this value can be changed if needed/requested. TODO: Need to add a proper setter for the userName
 */
data class LiveLikeUser(val userId: String, val userName: String)